### ISSUE TITLE
not able to call map inside preExpanded; preExpanded works when I hard code an array.

### ISSUE THREAD

**Issue by ashankar-fiserv** [springload/react-accessible-accordion#323] opened 2021-07-19 06:18 UTC
Hi, 

I'm calling map inside preExpanded.  

```
<Accordion
      allowZeroExpanded
      allowMultipleExpanded
      preExpanded={consumerGroups.map((consumerGroup, index) => 
                              (consumerGroup.name))}
>
      {consumerGroups.map((consumerGroup, index) => (
          <AccordionItem key={consumerGroup.name} uuid={consumerGroup.name} >
              ...
          </AccordionItem>
      ))}
</Accordion>
```

consumerGroup.name is a uuid string.  

I've printed out the array inside preExpanded, and it looks like this: 

`preExpanded: 6a8f9f53-92e5-48f8-b353-cdd18990bc8f,eede20b6-cdca-4503-ae05-34bc9a98e7aa,c7d86115-793f-4116-93bc-9cd89c36bd29`

It doesn't work though.  

If I hard code an array for preExpanded, `preExpanded={["fa86b1ff-f007-4e98-9a6b-c6673aa4e99f"...]}`, it works just fine.  

Am I doing something wrong?

**Comment by holloway** [comment] 2021-07-19 08:59
That code looks fine. Which version of RAA are you using?

`react-accessible-accordion` (RAA) or any React component can't tell you're using a `.map` to provide the value for a prop. That is resolved by the JavaScript engine itself, and then given to RAA as a value, so we can't tell how you're generating that array.

As it works when you hardcode it's probably not an issue with RAA.

However you could try debugging it by writing something like (the following code is untested),

```javascript
const preExpandedUuids = consumerGroups.map((consumerGroup, index) => (consumerGroup.name));

console.log({
  isArray: Array.isArray(preExpandedUuids),
  preexpandedUuidsJSON: JSON.stringify(preExpandedUuids),
  uuidTypes: preExpandedUuids.map(consumerGroupName => (typeof consumerGroupName),
});

// later in your code
preExpanded={preExpandedUuids}
```

Look at that `console.log` for anything unusual like non-arrays, array items that aren't strings, or unexpected whitespace in the strings.

Try

**Comment by ashankar-fiserv** [comment] 2021-07-19 22:18
Hi Matthew, 

Thank you for the reply.  

version 3.3.4

The distinguishing factor doesn't seem to be whether I run map or not, but whether I use a const array or not.  

If I have a dynamic array and then run map on this array in preExpanded, it doesn't work.  

If I use a const array and then run map on this const array in preExpanded, it works.  

https://codesandbox.io/s/divine-rgb-pq6x9?file=/src/App.tsx

**Comment by holloway** [comment] 2021-07-19 23:56
Ah the issue is that you're modifying preExpanded **after** the accordion has mounted.

As noted

> As the docs say the preExpanded list of uuids must be set when RAA is mounted (_"uuid prop matches any one of these strings will be expanded on mount."_).

You have three basic options,

1. Don't mount RAA until you calculate `preExpanded`. This what I recommend as the best option.
2. Use a React `key={preExpandedUuids.join()}` to force an unmount/mount cycle when the preExpandedUuids change. This should only be used if you can quickly resolve the preExpandedUuids very quickly. See https://www.nikgraf.com/blog/using-reacts-key-attribute-to-remount-a-component for the pattern to force mounting based on key changes. 
3. Don't use preExpanded, and instead manually manage state with `dangerouslySetExpanded`. This isn't recommended unless you really have no other way.

**Closed by holloway** 2021-07-19 23:56 UTC

**Comment by holloway** [comment] 2021-07-20 00:06
By the way @ashankar-fiserv in TypeScript you shouldn't use `as` unless you really need to. The following pattern should let you avoid writing `as ConsumerGroupProps[]`.

```
  const [isConsumerGroupsComplete, setIsConsumerGroupsComplete] = useState<boolean>(false);

  const [consumerGroups, setConsumerGroups] = useState<ConsumerGroupProps[]>([]);

```

**Comment by ashankar-fiserv** [comment] 2021-07-20 03:02
In my actual code, I have an add button onClick method which adds elements to the array.  

```
function addConsumerGroup() {
    let consumerGroup = {name: uuid()};
    consumerGroups.push(consumerGroup);
    setConsumerGroups([...consumerGroups]);
}

useEffect(()=> {
    console.log("useEffect which is dependent on consumerGroups.");
}, [consumerGroups]);

return (
   <>
       <Accordion
      allowZeroExpanded
      allowMultipleExpanded
      preExpanded={consumerGroups.map((consumerGroup, index) => 
                              (consumerGroup.name))}>
      {consumerGroups.map((consumerGroup, index) => (
          <AccordionItem key={consumerGroup.name} uuid={consumerGroup.name} >
              ...
          </AccordionItem>
      ))}
   </>
)
```

I assumed that for my code (and even for the code sandbox example without the add button onClick method), that the component would be re-rendered whenever the array changed and useEffect would be getting called and that the uuids for preExpanded would have been calculated when the RAA is mounted.

I have to understand the order of operations.

**Comment by ashankar-fiserv** [comment] 2021-07-20 04:36
I added a `isUuidCalculationComplete` state variable.  I based the rendering of the accordion on isUuidCalculationComplete.  

useEffect is called twice when consumerGroups/isUuidCalculationComplete changes.  

function addConsumerGroup() {
    let consumerGroup = {name: uuid()};
    consumerGroups.push(consumerGroup);
    setConsumerGroups([...consumerGroups]);
    setIsUuidCalculationComplete(false);
}

useEffect(()=> {
    console.log("useEffect which is dependent on consumerGroups.");
    setIsUuidCalculationComplete(true);
}, [consumerGroups, isUuidCalculationComplete]);

return (
   <>
       {isUuidCalculationComplete && <>
       <Accordion
      allowZeroExpanded
      allowMultipleExpanded
      preExpanded={consumerGroups.map((consumerGroup, index) => 
                              (consumerGroup.name))}>
      {consumerGroups.map((consumerGroup, index) => (
          <AccordionItem key={consumerGroup.name} uuid={consumerGroup.name} >
              ...
          </AccordionItem>
      ))}
      </>}
   </>
)
