### ISSUE TITLE
Possibility to use h tags instead of role="heading" and aria-level

### ISSUE THREAD

**Issue by sebpettersson** [springload/react-accessible-accordion#249] opened 2020-02-11 11:10 UTC
["When possible, use native heading mark-up directly. For example, it is preferable to use `<h1>` rather than using `<div role="heading" aria-level="1">`"
](https://www.w3.org/WAI/WCAG21/Techniques/aria/ARIA12.html#description)

It would be great to use semantically correct markup instead of relying on aria attributes. 

Likewise, `<div role="button" tabindex="0">"` could just be `<button>`.

This is how [the accordion example on w3.org](https://www.w3.org/TR/wai-aria-practices-1.1/examples/accordion/accordion.html) is set up.

**Comment by holloway** [comment] 2021-05-25 22:51
I believe this was done intentionally to avoid inheriting any styles, but I see your point.

**Comment by synecdokey** [comment] 2022-07-17 23:03
Duplicate of #322

**Closed by synecdokey** 2022-07-17 23:03 UTC
